name: Deploy to Tomcat

on:
  workflow_run:
    workflows: ["Java CI with Maven"]  # must match the CI workflow `name`
    types:
      - completed
  workflow_dispatch:  # still allows manual triggering

jobs:
  build-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin # Specify the Java distribution
        java-package: jdk

    # Step 3: Build the project (e.g., using Maven)
    - name: Build with Maven
      run: mvn clean package

    - name: Verify Secret URL
      run: |
        if [ -z "${{ secrets.NGROK_URL }}" ]; then
          echo "Secret NGROK_URL is not set."
          exit 1
        else
          echo "Secret NGROK_URL is set."
          curl -I "${{ secrets.NGROK_URL }}" || echo "Failed to connect to the secret URL."
        fi
    # Step 4: Create WAR file
    - name: Create WAR file manually
      run: |
        mkdir -p target/tmpwar
        cp src/main/resources/index.html target/tmpwar/
        cd target/tmpwar
        jar -cvf ../index.war .

    # Step 5: Check if access to Tomcat server
    - name: Test connectivity to Tomcat
      run: curl "${{ secrets.NGROK_URL }}"

    # Step 6: Deploy to Tomcat
    - name: Deploy to Tomcat
      run: |
        curl -T target/index.war "${{ secrets.NGROK_URL }}/manager/text/deploy?path=/index&update=true" \
        --user Java14:qcT34Ob
        
    - name: Wait for deployment
      run: sleep 25

    - name: Post-deploy check
      run: |
        curl -f "${{ secrets.NGROK_URL }}/index/" || exit 1
