name: Deploy to Tomcat

on:
  workflow_run:
    workflows: ["ci.yml"]
    types:
      - success
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'

    # Step 3: Build the project (e.g., using Maven)
    - name: Build with Maven
      run: mvn clean package

    # Step 4: Deploy to Tomcat
    - name: Deploy to Tomcat
      run: |
        curl -T target/App1.war "http://localhost:8080/manager/text/deploy?path=/App1&update=true" \
        --user Java14:qcT34Ob
